export const ADANA_NODES = [
  {
    id: 1,
    title: "Taşköprü ve Seyhan Nehri",
    coordinates: [36.9866, 35.3341],
    baseYear: 300,
    category: "Sosyal Hafıza",
    description: "Roma İmparatorluğu döneminden beri kenti ikiye bölen ve birleştiren köprü. Etrafındaki nehir kıyısı 1950'ler ve sonrasında halkın kanal ve nehirde yüzme kültürünün, sosyal hayatın ana mekanı olmuştur.",
    image: "https://images.unsplash.com/photo-1549221199-a6fedf0b0980?w=800&q=80",
    simulationImpact: { kultural: 10, ekonomik: 5, sosyal: 30 },
  },
  {
    id: 2,
    title: "Büyüksaat ve Kazancılar Çarşısı",
    coordinates: [36.9845, 35.3283],
    baseYear: 1882,
    category: "Ekonomik Hafıza",
    description: "Türkiye'nin en uzun saat kulesi ve etrafında şekillenen geleneksel zanaat, bakırcılık ve yeme-içme kültürü. Eski ahilik geleneğinin ve kentli burjuvaziden farklı, geleneksel esnaf kültürünün kalbi.",
    image: "https://images.unsplash.com/photo-1590059527376-79ef8826d9c6?w=800&q=80",
    simulationImpact: { kultural: 15, ekonomik: 25, sosyal: 10 },
  },
  {
    id: 3,
    title: "Milli Mensucat Fabrikası",
    coordinates: [36.9877, 35.3204],
    baseYear: 1907,
    category: "Endüstriyel Hafıza",
    description: "Orhan Kemal'in 'Murtaza' ve 'Bekçi Murtaza' gibi eserlerine ilham veren, Çukurova'nın ilk büyük pamuklu dokuma fabrikası. Binlerce işçinin emeğini barındıran bu devasa alan günümüzde Adana Müze Kompleksi'ne dönüştürülerek radikal bir palimpsest örneği sergilemektedir.",
    image: "https://images.unsplash.com/photo-1513828583688-c52646db42da?w=800&q=80",
    simulationImpact: { kultural: 5, ekonomik: 35, sosyal: 30 },
  },
  {
    id: 4,
    title: "Tepebağ Evleri",
    coordinates: [36.9868, 35.3289],
    baseYear: 1500,
    category: "Mekansal Hafıza",
    description: "Kentin ilk kurulduğu höyük üzerinde yer alan, dar sokakları ve cumbalı eski Adana evleriyle ünlü mahalle. Çoğunlukla yıkılmış veya soylulaştırılmış olsa da eski komşuluk kültürünün başlıca temsil alanıdır.",
    image: "https://images.unsplash.com/photo-1518155255470-3944ab82e5b8?w=800&q=80",
    simulationImpact: { kultural: 20, ekonomik: 5, sosyal: 15 },
  },
  {
    id: 5,
    title: "Yazlık Sinemalar (Sular Yolu)",
    coordinates: [37.0019, 35.3261],
    baseYear: 1960,
    category: "Kültürel Hafıza",
    description: "1960'lar ve 70'ler Adana'sının efsanevi yazlık sinema kültürü. Frigo yenilen, tahta sandalyeli bu açık hava sinemaları kentin en büyük sosyalleşme dinamiğiydi; bugün yerini çok katlı yapılara bırakmıştır.",
    image: "https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=800&q=80",
    simulationImpact: { kultural: 35, ekonomik: 10, sosyal: 25 },
  },
  {
    id: 6,
    title: "Ziyapaşa Bulvarı",
    coordinates: [36.9980, 35.3245],
    baseYear: 1970,
    category: "Sosyo-Ekonomik Hafıza",
    description: "Adana'nın erken Cumhuriyet ve sonrası modernleşme vizyonunu, yeni kent burjuvazisini, eğlence mekanlarını ve lüks tüketimi temsil eden palmiye ağaçlarıyla süslü ana arteri.",
    image: "https://images.unsplash.com/photo-1449844908441-8829872e2607?w=800&q=80",
    simulationImpact: { kultural: 10, ekonomik: 20, sosyal: 15 },
  },
  {
    id: 7,
    title: "Eski Tren Garı",
    coordinates: [36.9972, 35.3213],
    baseYear: 1912,
    category: "Göç ve Endüstri",
    description: "Çukurova'ya çalışmak için gelen on binlerce mevsimlik tarım işçisinin (elçiler) şehre giriş yaptığı ilk toplanma mekanı. Orhan Kemal edebiyatının işçi sınıfı giriş kapısı.",
    image: "https://images.unsplash.com/photo-1474487548417-781cb71495f3?w=800&q=80",
    simulationImpact: { kultural: 10, ekonomik: 25, sosyal: 25 },
  },
  {
    id: 8,
    title: "Karataş Yolu Pamuk Tarlaları",
    coordinates: [36.9610, 35.3320],
    baseYear: 1950,
    category: "Tarımsal Hafıza",
    description: "Yaşar Kemal ve Orhan Kemal eserlerine konu olan 'Beyaz Altın' tarlaları. Günümüzde kentin güneye doğru kontrolsüz genişlemesi sonucu devasa beton plazalara dönüşerek hafızasını yitirmiştir.",
    image: "https://images.unsplash.com/photo-1590400812739-166244df88a3?w=800&q=80",
    simulationImpact: { kultural: 5, ekonomik: 35, sosyal: 10 },
  },
  {
    id: 9,
    title: "Eski Sebze Hali ve Tablakarlar",
    coordinates: [36.9820, 35.3210],
    baseYear: 1930,
    category: "Ekonomik Hafıza",
    description: "Kentin alt gelir grubunun ve sokak esnafının en hareketli merkezi. 'Tablakar' (seyyar satıcı) kültürünün, şırdancılığı ve sokak lezzetlerini kent geneline yayan hareketli mekanizmanın beşiği.",
    image: "https://images.unsplash.com/photo-1533900298318-6b8da08a523e?w=800&q=80",
    simulationImpact: { kultural: 15, ekonomik: 30, sosyal: 20 },
  },
  {
    id: 10,
    title: "Yeni Adana (Turgut Özal Bulvarı)",
    coordinates: [37.0425, 35.3195],
    baseYear: 1990,
    category: "Modern Kentleşme",
    description: "Eski kent merkezinin (Güney) tamamen terk edilerek, tarım arazilerinin üzerine kurulan grid planlı dev apartman blokları. Palimpsestin en üst ve amnezik (hafızasız) tüketim katmanı.",
    image: "https://images.unsplash.com/photo-1444723121867-7a241cacace9?w=800&q=80",
    simulationImpact: { kultural: 10, ekonomik: 25, sosyal: 15 },
  }
];
